### ISSUE TITLE
SetItemsFromMenu Obsolete

### ISSUE THREAD

**Issue by rheckart** [pocheshire/BottomNavigationBar#12]
The example on the project's home page shows using SetItemsFromMenu, but the compiler shows a warning indicating obsolete, deprecated. What is the proper way to set the menu items?

**Comment by pocheshire** [comment]
@rheckart right way is use

```
_bottomBar.SetItems(Resource.Menu.bottombar_menu);
_bottomBar.SetOnMenuTabClickListener (this);
```

instead SetItemsFromMenu.

I removed obsolete method from example
