### ISSUE TITLE
Error inflating class

### ISSUE THREAD

**Issue by Iliort** [pocheshire/BottomNavigationBar#13]
I wanna set the bar up in my app but it gives an exception when it reaches the line `_bottomBar.SetItems(Resource.Menu.bottombar_menu);`.
The exception is **"Android.Views.InflateException: Binary XML file line #1: Error inflating class \<unknown\>"**.
What may this problem be about?

**Comment by pocheshire** [comment]
@Iliort Can you provide your bottombar_menu.xml file?

**Comment by Iliort** [comment]
@pocheshire At first I thought that problem was associated with it too. So trying to debug it I used the one from your sample but the error remained the same.

Anyway, here is it but I guess you're kinda familiar with it)

[bottombar_menu.zip](https://github.com/pocheshire/BottomNavigationBar/files/337240/bottombar_menu.zip)

**Comment by pocheshire** [comment]
@Iliort So, I can't repeat this.

- What you do before `_bottomBar.SetItems(Resource.Menu.bottombar_menu);` invoked?
- Can you repeat exception in demo sample?
- Have you tried "standard" steps after change bottombar_menu.xml (delete "bin" and "obj" folders and clean-rebuild solution)?

**Comment by Iliort** [comment]
@pocheshire 
1. I tried to use the exact code from your sample but the exception kept appearing.
2. But demo works fine
3. I tried deleting (doesn't work)

It seems like it may be about some application settings but I tried to copy from the demo as much as possible (the manifest, resources, etc.). Maybe you can try to create the bar in a totally clear project (just the bar and nothing else). If it works, I will just be able to compare it with mine and see what's different.
Thanks in advance)

**Comment by pocheshire** [comment]
@Iliort ok, I'll try create clean project. One more question – what version of BottomBar you use"?

**Comment by Iliort** [comment]
@pocheshire 1.1.2
I downloaded it via NuGet

**Comment by pocheshire** [comment]
@Iliort See [this](https://github.com/i-1213/Demo) sample. It was created for other issue but it's clean solution and it doesn't contains it bug.

Maybe the reason for a bug in the device? On what device you are testing project?

**Comment by Iliort** [comment]
@pocheshire I'll check out the demo, thanks! I run it on LG G4 (Android 5.1). But I don't think this is a problem since your sample works fine there.

**Comment by rileytaylor** [comment]
@pocheshire I am having this issue as well, on the same point (_bottombar.SetItems) both if I attempt to define my menu in code or in .axml. I've followed your sample/readme instructions in adding it to my project.

**Comment by pocheshire** [comment]
@rileytaylor can you provide your project?

**Comment by pocheshire** [comment]
@Iliort problem persists?

**Comment by rileytaylor** [comment]
@pocheshire Yep, here it is. Not much else implemented aside from some mvvmlight and a little bit of UI.
[StatusBoardApp.Droid.zip](https://github.com/pocheshire/BottomNavigationBar/files/354623/StatusBoardApp.Droid.zip)

**Comment by pocheshire** [comment]
@Iliort @rileytaylor 
SOLVED

You MUST use AppCompat Theme in your app

[See how it work] (https://github.com/pocheshire/BottomNavigationBar/files/355485/StatusBoardApp.Droid.zip) (more interesting is style.xml and AndroidManifest.xml)

**Comment by ice-j** [comment]
This still bothers me, why am I bound to the AppCompat theme? @pocheshire  ?

**Comment by pocheshire** [comment]
@ice-j [answer](https://chris.banes.me/2014/10/17/appcompat-v21/)

**Comment by cullenjohnson** [comment]
Thanks @pocheshire ! You saved me a headache. :)
