### ISSUE TITLE
Can't change inactive color

### ISSUE THREAD

**Issue by Hary25** [pocheshire/BottomNavigationBar#16]
i cant change inactive color on bottom navigation, anyone can help?

**Comment by pocheshire** [comment]
@Hary25 

in fixed mode:
`_bottomBar.SetFixedInactiveIconColor("#ffffff");`

in shifting mode you can't change inactive color, because in this mode inactive color it's `_bottomBar.SetShiftingIconColor("#ffffff");` with alpha
