### ISSUE TITLE
Version of dependencies

### ISSUE THREAD

**Issue by ice-j** [pocheshire/BottomNavigationBar#24]
Hi, as you already know, we're using this component with Xamarin.Forms too.

Suddenly the current stable package of Xamarin.Forms does not support any of the dependencies listed below because it's working on 23.3.0, so we're stuck with v1.1.2. Can we maybe revert the dependencies to the previous versions if it does not break anything?

The current Dependencies (since v1.1.3):

Xamarin.Android.Support.Animated.Vector.Drawable (>= 23.4.0)
Xamarin.Android.Support.Design (>= 23.4.0)
Xamarin.Android.Support.v4 (>= 23.4.0)
Xamarin.Android.Support.v7.AppCompat (>= 23.4.0)
Xamarin.Android.Support.v7.RecyclerView (>= 23.4.0)
Xamarin.Android.Support.Vector.Drawable (>= 23.4.0)

Thanks in advance.

**Comment by nbsoftware** [comment]
+1
 I'm in the very same situation.

**Comment by pocheshire** [comment]
Ok, thanks for PR, I'll merge it today and update NuGet. Also, I will consider it when porting 2+ version which I have already started, and finish the plan in late October.

**Comment by pocheshire** [comment]
In Xamarin.Forms you should use 1.4.0.2 version

**Comment by Monomachus** [comment]
@pocheshire What are the actions to port to version 2+, perhaps I can help you with that if needed?

**Comment by pocheshire** [comment]
@Monomachus sorry for long time waiting answer. There are two way up version to 2+. First, commit by commit port all changes from source repo. Second, forget all what suggest first way and port changes only from last source repository commit
