### ISSUE TITLE
Provide properties to set BarBackground and inactive icon color in fixed Mode

### ISSUE THREAD

**Issue by escamoteur** [pocheshire/BottomNavigationBar#27]
Hi,

I'm working on extending the Xamarin.Forms version of Bottombar. I'm struggling to set the Bar background color to black and figred the only way is to call                    _bottomBar.UseDarkThemeWithAlpha(true); and add a color definition for 
bb_darkBackgroundColor in my colors.xml.

Also I found that setting "white" in the colors.xml changes the inactive icons in darcktheme.

I think it would be much more comfortable to expose this color as a property that can be set directly.

What do you think?

Best
Thomas

**Comment by pocheshire** [comment]
Hi, 

Maybe in version 2.0

**Comment by zonkzen** [comment]
Also, this approach reserves "white" color and many times it actually has to be set to something else than "#FFFFFF". It would be good to give it a more meaningful name or at least a prefix like for 'bb_darkBackgroundColor'.

**Comment by pocheshire** [comment]
`white` renamed to `bb_darkInActiveBottomBarItemColor` in 1.4.0.3 version
