### ISSUE TITLE
Scrollable tabs while tab items more than 5 or 6.

### ISSUE THREAD

**Issue by rzee7** [pocheshire/BottomNavigationBar#28]
@pocheshire It would be great if you could add scroll or More button to tab items while they are more than 5 or 6 or more, like in iOS we have More button.

**Comment by pocheshire** [comment]
> It would be great if you could add scroll or More button to tab items while they are more than 5 or 6 or more

No, bottom navigation should be used for:

> * Three to five top-level destinations of similar importance (alternative: a persistent navigation drawer accessible from anywhere in the app)
> * Destinations requiring direct access from anywhere in the app (alternative: tabs for only one or two destinations)

https://material.google.com/components/bottom-navigation.html#bottom-navigation-usage


>  like in iOS we have More button.

You can add your own More button.
