### ISSUE TITLE
problem on new google apis update

### ISSUE THREAD

**Issue by halukmy** [pocheshire/BottomNavigationBar#33]
can you check it?

**Comment by bchaitani** [comment]
Any solution for this issue?

**Comment by jpozo20** [comment]
#35 
I think I know what the problem is. I'll be working on a fork while the author answers the issues.

**Comment by jpozo20** [comment]
Please, try this package and tell meif it works.

[jpozo.BottomNavigationBar-Nougat.1.4.0.2.zip](https://github.com/pocheshire/BottomNavigationBar/files/604875/jpozo.BottomNavigationBar-Nougat.1.4.0.2.zip)

**Comment by modplug** [comment]
@jpozo20  Please make a this a PR

**Comment by jpozo20** [comment]
@modplug I think the autor downgrades the libraries version so Xamarin.Forms could be supported. What I did was updated to the latests libraries and I think that would be a breaking change.

**Comment by pocheshire** [comment]
fixed in 1.4.0.3 version
