### ISSUE TITLE
Update refs to v24

### ISSUE THREAD

**Issue by jpozo20** [pocheshire/BottomNavigationBar#35]
It looks like there were some changes with the resources in Nougat 7.0, so if you're targeting Nougat or you have the v24 libraries from Xamarin the build will fail because some resources that are in the BottomNavigationBar do not exists anymore. 

I think it's only a thing of updating the referenced Xamarin libraries. 
Took me a couple of hours trying to figure what was exactly the problem though.

**Comment by pocheshire** [comment]
fixed in 1.4.0.3 version

**Comment by modplug** [comment]
Just a heads up that support libs 25-rc was released yesterday
