### ISSUE TITLE
Bottom Bar tabs come over Keyboard when search view is clicked

### ISSUE THREAD

**Issue by glalwani2** [pocheshire/BottomNavigationBar#4]
Hi,
Since I am using your library and thank you guys for this open source project.
I am facing one more issue.I have used for the time being Bottom navigation in my main activity and I have a searchview in toolbar which comes out when icon is clicked.
The problem is the bottom bar tabs come over the keybaord and the screen size becomes very less.
So what should be the best approach for this.I am not sure if I have to hide the bottom bar or something is their in design guidelines.Any help will be much appreciated.

So the guidelines say,

Bottom sheets, navigation drawers, and keyboards appear in front of the bottom navigation bar, temporarily covering it.

So how do we attain this, can you tell me?
Thank you

**Comment by pocheshire** [comment]
@glalwani2 Can you create test project with this bug and upload to GitHub?

**Comment by glalwani2** [comment]
@pocheshire  The tabs comes above the keyboard, so what I did is when clicking the search icon, I am hiding the bottom bar and again showing it when searchview is gone, for the time being I did like this.Since bottom bar takes the space of the view to which it is attcahed, therefore when I attached the bottom bar to my viewpager, then my view pagers items where coming behind my appbarlayout, therefore for the time being I had to give margin to my ViewPager.

**Comment by pocheshire** [comment]
@glalwani2 Try attaching the BottomBar to [container](https://github.com/roughike/BottomBar/issues/122#issuecomment-206322313) that contains ViewPager.
And I still need an example that reproduces these bugs to fix them

**Comment by pocheshire** [comment]
@glalwani2 try add attribute '[Activity(WindowSoftInputMode=SoftInput.AdjustPan)]' to your activity
