### ISSUE TITLE
1.4.0.3 and Xamarin.Forms: Not compatible

### ISSUE THREAD

**Issue by markmadlangbayan** [pocheshire/BottomNavigationBar#40]
1.4.0.3 now requires Android support libraries >= 24.2.1.  Unfortunately, Xamarin.Forms only supports 23.3.0 right now.  Is the 24.2.1 requirement necessary?  

Thanks!

**Comment by pocheshire** [comment]
Yes 1.4.0.3 breaks support Xamarin.Forms. You should use 1.4.0.2 version
