### ISSUE TITLE
Change background color of Bottom Bar

### ISSUE THREAD

**Issue by glalwani2** [pocheshire/BottomNavigationBar#5]
Hi,
I need my bottom bar to have jet black background with icons given as png images( that are in white ) and when it anyone is selected( the image should change ). I am not sure if we can do that in this library.
But what i Was trying I used the UseDarkTheme() and the bottom bar had dark grey background and the color of my icons  changed to grey from transparent(as they are png).
How i Can make my bottom bar background color black and at the same time keep my pngs as it is or change them to white.

**Comment by pocheshire** [comment]
`_bottomBar.UseDarkTheme();`
and
`_bottomBar.SetActiveTabColor(global::Android.Graphics.Color.White);`

**Comment by glalwani2** [comment]
No But I want my Inactive icons color as White and Active Icons color as red.and the background of bottombar as black. Currently using UseDarkTheme() makes the background color of bottombar as dark grey and default icon color as light grey.

**Comment by pocheshire** [comment]
Then you should use `_bottomBar.UseDarkTheme();` and `_bottomBar.SetActiveTabColor(global::Android.Graphics.Color.Red);` (or any color in `SetActiveTabColor(...)`).
 You [can't customize](https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-style) icons in inactive state

**Comment by glalwani2** [comment]
But thats the problem, the _bottomBar.UseDarkTheme(); makes the bottom bar background dark grey and the icons color as light grey i need them black background with white icons.If you get my point. Please help.

**Comment by pocheshire** [comment]
I found a solution.
For change bottom bar background in dark theme mode add in color.xml:
`<color name="bb_darkBackgroundColor">#000000</color>` 
then use method `_bottomBar.UseDarkThemeWithAlpha(false);` I added in 1.0.9 version

**Comment by glalwani2** [comment]
Thank you so much Pocheshire for this enhancement. I am very grateful to you for this.
