### ISSUE TITLE
Change The Items front colors

### ISSUE THREAD

**Issue by Xiryl** [pocheshire/BottomNavigationBar#58]
Hi,

how its possible to change the text color of the item in the menu?

i try to add the textcolor, but it dosent work, its always gray. idem the icon.

` <item
      android:id="@+id/bb_menu_favorites"
      android:title="Manage Licenses"
      android:icon="@drawable/ic_settings"     
      android:textColor="#ff0000"/>`

how i can change the color of the text?

thanks.

**Comment by Lanseer** [comment]
I got the same problem with yours, is there any solutions?

**Comment by Xiryl** [comment]
add this in `colors.xml`
> <color name="bb_darkBackgroundColor">#e1461e</color>

than follow [https://github.com/pocheshire/BottomNavigationBar/issues/5](url)

 my code example
```
     _bottomBar = BottomBar.Attach(this, savedInstanceState);
                _bottomBar.UseFixedMode();
                _bottomBar.UseDarkThemeWithAlpha(false);
                _bottomBar.SetBackgroundColor(Color.AliceBlue);
                _bottomBar.SetItems(Resource.Menu.bottombar_menu);
                _bottomBar.HideShadow();
                _bottomBar.SetActiveTabColor("#ffffff");
                _bottomBar.SetOnMenuTabClickListener(this);
```
