### ISSUE TITLE
Badges Problem

### ISSUE THREAD

**Issue by glalwani2** [pocheshire/BottomNavigationBar#6]
Hi Pochehire,
I am facing two problems with badges which I want to highlight here 

1) When I try to set badge from a fragment then the badges circle becomes bit elliptical and it looks the image is stretched, but when I add through the activity in which the bottombar is instantiated(and just below bottom bar is filled with xml) the badge looks like a perfect circle, so why if I set from fragment taking reference of the bottom bar it becomes elliptical?

2) The badge's circle comes on the top right side of the bottom bar icon, can I make the badge appear on the top left corner( the opposite) ?

Thank you again for the awesome library, I just want to use it in my project and update your README.

Thanks!

**Comment by pocheshire** [comment]
Hi @glalwani2 

1) I'm working on solution.

2) Solved. In version 1.0.11 you will able to use use property "Position" for set badge location to the right or to the left in tab. For more info see demo project.

**Comment by pocheshire** [comment]
1) Solved. Update will be today.
