### ISSUE TITLE
Question: How to use it in the Xamarin.Forms way?

### ISSUE THREAD

**Issue by Yaojian** [pocheshire/BottomNavigationBar#7]
I have an Xamarin.Forms application and want to use this navigation bar .

**Comment by pocheshire** [comment]
You probably need to write a new renderer

[link1](http://forums.xamarin.com/discussion/66975/android-bottom-navigation-bar-following-new-google-guidelines) [link2](https://blog.xamarin.com/embedding-native-controls-into-xamarin-forms/)

I'll think about adding support Xamarin.Forms soon

**Comment by sschmidt** [comment]
Great project!
I implemented a Xamarin.Forms renderer for BottomNavigationBar, it's over here: https://github.com/thrive-now/BottomNavigationBarXF

**Comment by adrianknight89** [comment]
I couldn't get the XF port working. Seemed unusable to me.
